Uploading CSV

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving student_placement_career_success_dataset_2026.csv to student_placement_career_success_dataset_2026.csv

Checking in python if file is there or not

In [ ]:
import os

os.listdir()

['.config', 'student_placement_career_success_dataset_2026.csv', 'sample_data']

Loading CSV

In [ ]:
import pandas as pd

df = pd.read_csv('student_placement_career_success_dataset_2026.csv')

Seeing how the data looks like

In [ ]:
df.head()

,Age,Gender,College_Tier,Specialization,CGPA,DSA_Problems_Solved,Internships,Certifications,Projects_Count,Communication_Skills,Aptitude_Test_Score,LeetCode_Rating,GitHub_Contributions,Hackathons_Participated,AI_ML_Skill_Level,System_Design_Knowledge,Resume_Score,Mock_Interview_Score,Placement_Status,Salary_LPA
0,19,Male,Tier 3,AI/ML,7.70,229,0,1,11,87,46,1676,241,6,1,1,50,62,1,9.99
1,21,Other,Tier 3,Civil,6.97,486,0,10,12,74,88,1718,82,3,8,10,62,35,1,13.06
2,20,Other,Tier 2,Electronics,6.74,180,0,5,2,45,83,1534,0,1,6,6,83,68,1,7.74
3,18,Other,Tier 2,Computer Science,6.64,98,4,6,2,75,72,1559,47,5,10,4,90,43,1,12.29
4,18,Other,Tier 2,Electronics,8.67,216,4,3,2,64,70,1473,6,7,6,3,68,80,1,14.45

Checking Dataset structure

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19999 entries, 0 to 19998
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      19999 non-null  int64
 1   Gender                   19999 non-null  object
 2   College_Tier             19999 non-null  object
 3   Specialization           19999 non-null  object
 4   CGPA                     19999 non-null  float64
 5   DSA_Problems_Solved      19999 non-null  int64
 6   Internships              19999 non-null  int64
 7   Certifications           19999 non-null  int64
 8   Projects_Count           19999 non-null  int64
 9   Communication_Skills     19999 non-null  int64
 10  Aptitude_Test_Score      19999 non-null  int64
 11  LeetCode_Rating          19999 non-null  int64
 12  GitHub_Contributions     19999 non-null  int64
 13  Hackathons_Participated  19999 non-null  int64
 14  AI_ML_Skill_Level        19999 non-null  int64
 15  System_Design_Knowledge  19999 non-null  int64
 16  Resume_Score             19999 non-null  int64
 17  Mock_Interview_Score     19999 non-null  int64
 18  Placement_Status         19999 non-null  int64
 19  Salary_LPA               19999 non-null  float64
dtypes: float64(2), int64(15), object(3)
memory usage: 3.1+ MB

Checking data quality

In [ ]:
df.describe()

,Age,CGPA,DSA_Problems_Solved,Internships,Certifications,Projects_Count,Communication_Skills,Aptitude_Test_Score,LeetCode_Rating,GitHub_Contributions,Hackathons_Participated,AI_ML_Skill_Level,System_Design_Knowledge,Resume_Score,Mock_Interview_Score,Placement_Status,Salary_LPA
count,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.000000,19999.0,19999.000000
mean,21.506575,7.202910,253.276364,1.450123,5.012651,6.503725,70.154758,67.489374,1452.653883,121.610431,3.993250,5.498175,5.490525,72.318416,67.480674,1.0,12.433688
std,2.295402,1.005051,144.133370,1.160273,3.149616,3.437929,17.701622,18.995256,340.895467,74.907578,2.586614,2.867160,2.856539,16.267876,19.030763,0.0,2.468158
min,18.000000,4.500000,0.000000,0.000000,0.000000,1.000000,40.000000,35.000000,800.000000,0.000000,0.000000,1.000000,1.000000,45.000000,35.000000,1.0,3.000000
25%,19.000000,6.520000,150.000000,0.000000,2.000000,3.000000,55.000000,51.000000,1210.000000,65.000000,2.000000,3.000000,3.000000,58.000000,51.000000,1.0,10.760000
50%,22.000000,7.210000,250.000000,1.000000,5.000000,7.000000,70.000000,67.000000,1447.000000,120.000000,4.000000,6.000000,5.000000,72.000000,67.000000,1.0,12.430000
75%,24.000000,7.880000,352.000000,2.000000,8.000000,9.000000,86.000000,84.000000,1684.000000,173.000000,6.000000,8.000000,8.000000,87.000000,84.000000,1.0,14.080000
max,25.000000,10.000000,841.000000,4.000000,10.000000,12.000000,100.000000,100.000000,2790.000000,478.000000,8.000000,10.000000,10.000000,100.000000,100.000000,1.0,21.860000

Checking categorical value

In [ ]:
print(df['Gender'].unique())

print(df['College_Tier'].unique())

print(df['Specialization'].unique())

['Male' 'Other' 'Female']
['Tier 3' 'Tier 2' 'Tier 1']
['AI/ML' 'Civil' 'Electronics' 'Computer Science' 'Information Technology'
 'Data Science' 'Mechanical']

Using One hot encoding

In [ ]:
df_encoded = pd.get_dummies(
    df,
    columns=['Gender', 'College_Tier', 'Specialization'],
    drop_first=True
)

df_encoded.head()

,Age,CGPA,DSA_Problems_Solved,Internships,Certifications,Projects_Count,Communication_Skills,Aptitude_Test_Score,LeetCode_Rating,GitHub_Contributions,...,Gender_Male,Gender_Other,College_Tier_Tier 2,College_Tier_Tier 3,Specialization_Civil,Specialization_Computer Science,Specialization_Data Science,Specialization_Electronics,Specialization_Information Technology,Specialization_Mechanical
0,19,7.70,229,0,1,11,87,46,1676,241,...,True,False,False,True,False,False,False,False,False,False
1,21,6.97,486,0,10,12,74,88,1718,82,...,False,True,False,True,True,False,False,False,False,False
2,20,6.74,180,0,5,2,45,83,1534,0,...,False,True,True,False,False,False,False,True,False,False
3,18,6.64,98,4,6,2,75,72,1559,47,...,False,True,True,False,False,True,False,False,False,False
4,18,8.67,216,4,3,2,64,70,1473,6,...,False,True,True,False,False,False,False,True,False,False

Creating X and Y

In [ ]:
X = df_encoded.drop('Salary_LPA', axis=1)

y = df_encoded['Salary_LPA']

print(X.shape)
print(y.shape)

(19999, 26)
(19999,)

Train - Test Split

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(15999, 26)
(4000, 26)

Training Random forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [ ]:
print(type(rf))

<class 'sklearn.ensemble._forest.RandomForestRegressor'>

Making predictions

In [ ]:
y_pred = rf.predict(X_test)

print(y_pred[:10])

[12.5551 15.9836 13.4906 14.3735 11.6262 10.8393 11.8265 11.0607 12.4223
 12.2759]

Measuring accuracy

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

rmse = mse ** 0.5

r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("RMSE:", rmse)
print("R2  :", r2)

MAE : 1.643693225
RMSE: 2.05945353054093
R2  : 0.3189932060339282

which features matter more for salary?

In [ ]:
import pandas as pd

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

print(feature_importance.head(10))

                 Feature  Importance
1                   CGPA    0.167527
11     AI_ML_Skill_Level    0.145503
3            Internships    0.111079
8        LeetCode_Rating    0.058811
2    DSA_Problems_Solved    0.055912
9   GitHub_Contributions    0.055327
13          Resume_Score    0.051213
14  Mock_Interview_Score    0.050434
6   Communication_Skills    0.049942
7    Aptitude_Test_Score    0.049723

checking for overfitting

In [ ]:
print("Train Score:", rf.score(X_train, y_train))
print("Test Score :", rf.score(X_test, y_test))

Train Score: 0.9038841207578018
Test Score : 0.3189932060339282

Improving model

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rf2 = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

rf2.fit(X_train, y_train)

print("Train Score:", rf2.score(X_train, y_train))
print("Test Score :", rf2.score(X_test, y_test))

Train Score: 0.5540015623983642
Test Score : 0.3359632888776529

Predicting for new student

In [ ]:
new_student = {}

for col in X.columns:
    value = float(input(f"Enter {col}: "))
    new_student[col] = value

new_student_df = pd.DataFrame([new_student])

predicted_salary = rf.predict(new_student_df)

print(f"\nPredicted Salary: {predicted_salary[0]:.2f} LPA")

Enter Age: 22
Enter CGPA: 8
Enter DSA_Problems_Solved: 0
Enter Internships: 3
Enter Certifications: 3
Enter Projects_Count: 10
Enter Communication_Skills: 70
Enter Aptitude_Test_Score: 45
Enter LeetCode_Rating: 1908
Enter GitHub_Contributions: 61
Enter Hackathons_Participated: 3
Enter AI_ML_Skill_Level: 9
Enter System_Design_Knowledge: 3
Enter Resume_Score: 79
Enter Mock_Interview_Score: 35
Enter Placement_Status: 1
Enter Gender_Male: 0
Enter Gender_Other: 0
Enter College_Tier_Tier 2: 0
Enter College_Tier_Tier 3: 0
Enter Specialization_Civil: 0
Enter Specialization_Computer Science: 0
Enter Specialization_Data Science: 0
Enter Specialization_Electronics: 1
Enter Specialization_Information Technology: 0
Enter Specialization_Mechanical: 0

Predicted Salary: 15.05 LPA